### ISSUE TITLE
Event Types Disappearing

### ISSUE THREAD

**Issue by thom-moresoda** [verbb/Events#124]
### Question

Hi

We have an issue where the Event Types are disappearing (and taking any live events with them)

**Steps to recreate:**

- The events plugin & setup (including adding Event Types) had been done on a feature branch & merged in to production
- When the production branch deployed to the live site, the Event Types were missing so were added locally & re-deployed
- The second deployment was successful & the Event Types were present on the live site
- A few events were added to each Event Type
- The next day, the Event Types had disappeared & removed the events

**Stuff I've looked in to:**

- The live site has admin changes set to off - I can't see any way a user could have accidentally removed them
- Nothing had been deployed to the site after the successful re-deployment

**Versions**
Craft 4.3.4
Events 2.0.0-beta.10

Any insight in to this would be appreciated 

Many thanks,
Thom

**Comment by engram-design** [comment]
That indeed seems bizarre. Event types wouldn't just delete themselves out of the blue, and would require `allowAdminChanges = true` to be possible.

Can you take a look in your `events_eventtypes` db table, and see if there are any extra entries? We don't support soft-deletion of event types, otherwise there would be a `dateDeleted` column to look at.

My only thought is that your project config is somehow out of sync. Maybe pulling from the production database, running `./craft project-config/rebuild` locally and making changes would help kick it back into shape?

**Comment by engram-design** [comment]
Closing due to age.
