### ISSUE TITLE
Feature request: two way linking between events (Many to Many plugin support?)

### ISSUE THREAD

**Issue by KatieMFritz** [verbb/Events#13]
I'm using Events for conferences and sessions (as separate event types). I'd love to be able to do two-way linking between conferences and sessions, instead of having to set the relationship from both entries.

For other element types, I use the Many to Many plugin (where [I've requested Events support](https://github.com/verbb/events)). Not sure if there's something you could do on your end though!

**Comment by KatieMFritz** [comment]
Any thoughts on this, Josh? I left another comment on my [Many to Many issue](https://github.com/Pageworks/craft-manytomany/issues/29) as well.

**Comment by engram-design** [comment]
We plan on revamping events to have multiple sessions, in the next major version (no ETA yet) - for this exact reason. You might have an event going for a week, with session times each night - right now, you'd need to create multiple events/tickets, which is tedious (a nightmare).

But right now, there's really no way to nest events, and the best you could do is use some event relational fields to hook things together in a custom fashion.

Does adding a session layer in an event sound like it'd be the right solution for your needs?

I've not even heard of the Many to Many plugin! I'd need to dive in for some further detail.

**Comment by KatieMFritz** [comment]
A session layer would work, but an even more broad parent/child relationship option might be better. There might also be a series of events, for example. 

Being able to nest Events as if they were a Structure would be perfect for me.

**Comment by engram-design** [comment]
Still open to this, but thinking it'll be solved with Event Sessions - https://github.com/verbb/events/issues/81.

Otherwise, there'd be nothing stopping you from adding an Events field to the Event Type you want to be able to nest on. It's more the UI for that isn't ideal.

The reason for the distinct middle layer would be that Events are similar to entries, in that they're the top-level content where you'd store content for everything about the event - location, images, url, etc. A session has the date/time information, capacity (and custom fields), along with multiple ticket definitions (availability, number per ticket).

However, if you're looking to "just" have hierarchy to events (as in - make it a structure), that's something we can do if you like. It's more that my thinking is those nested events (sessions in your example), kinda need to be different to the top-level event, as they store different content, probably don't specify their own URLs. If we were to look at how a Structure would work, you'd have an Event entry type and a Session entry type. Every level-1 entry would have the Event entry type, the level-2 entry a session. For content authors, that'd be a pain to manage, and you'd probably need to do the same in our scenario.

Happy to get some idea though as we want to add in this functionality so it suits everyone.

**Comment by engram-design** [comment]
Going to mark this as completed with the introduction of sessions in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3)
