### ISSUE TITLE
Download Tickets in Control Panel 

### ISSUE THREAD

**Issue by mihob** [verbb/Events#134]
### What are you trying to do?

It would be great if you could also download the ticket PDF in the Control Panel. 

Preferably at the commerce order and at the ticket / ticket index

### What's your proposed solution?

- Add a "Download Ticket" button in the detail view of the commerce order
- Add a "Download Ticket" button in the detail view of the ticket
- Add a "Download Ticket(s)" button in the index view of the purchased tickets for selected tickets

**Comment by engram-design** [comment]
The tricky part is that we're pretty limited with extending the order detail view, due to Commerce using Vue for that, but I'll look into some options. At the very least, we should be able to include an option next to the "Save" button for an order to download all tickets for an order. I'm not sure if we'll be able to pull off a "download ticket" for an individual PDF line item.

Don't forget that the "detail view of the ticket" isn't an appropriate place to download the PDF, as that's recorded against a purchased ticket. Or, maybe your second point was just referring to the first?

But I agree that including it on a purchased ticket detail page makes sense.

**Comment by mihob** [comment]
Yeah sorry, i meant the purchased ticket detail.

A button to download all tickets at the commerce order next to the "Save" button would be great. This would help our editors a lot if a buyer can no longer find his tickets (for whatever reason)

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
