### ISSUE TITLE
[Feature Request] TicketType "Title Format"

### ISSUE THREAD

**Issue by JustJarethB** [verbb/Events#23]
### Description
As you can set a Title Format like `{fieldHandleA} - {fieldHandleB}` on entry types, please allow a similar function for Ticket Types. 

### Use Case
Say we set up a generic ticket type which allows for a name to be given to it, along with other config settings on how to render it. This can be used to show in the front end reasonably well, but it would be nice, for things such as the default craft commerce checkout to be able to configure what name it will show per ticket (not per ticket type)

**Comment by johnj24** [comment]
I would like to see this as well. Our events have what we call "classes" and these "classes" are saved as an entry in Craft. They're in Craft as entries because we want to do more with them other than ticketing. We can add these entries under Ticket Fields and then hopefully write a simple dynamic title format to create ticket types based on the title of the entry.

**Comment by engram-design** [comment]
There's a slight technical complication here that Ticket Types are elements, unlike entry types (or event types) which are models that act as a container around the individual elements (what each ticket type is).

But, I think we can manage this in some form!

**Comment by stevecomrie** [comment]
+1 i was literally just here surfing the issues to recommend something like this if someone else hadn't already. super, super useful.

**Comment by engram-design** [comment]
Added in [3.0.0-beta.3](https://github.com/verbb/events/releases/tag/3.0.0-beta.3).
