### ISSUE TITLE
Ticket Check In

### ISSUE THREAD

**Issue by demoseed** [verbb/Events#39]
I have setup event ticket check In form on my site as describe in plugin doc.
    1. Everything working good. But I want to show error and success message on my site with my 
        extended layout.
        Like I want to show success and error message above my form.
    
    2. Second thing is when entered wrong SKU then php error occurs instead of show "You have 
          entered wrong sku."

For what can we do for this requirement? Please give me suggestion.

**Comment by engram-design** [comment]
Have you set a custom template for your "Check-in Template" (in the plugin settings)? Otherwise, it'll render the default template, with an error or success message - rather than a custom template you define.

For instance, if you have your template (as the [https://verbb.io/craft-plugins/events/docs/feature-tour/ticket-check-in#example-form](example) ) named `templates/checkin.html` - you'd enter `checkin` into this field in your settings.

That way, when you submit the form to the controller, it'll render your custom template instead.

**Comment by engram-design** [comment]
Closing due to age.
