### ISSUE TITLE
Ticket types missing from project config sync

### ISSUE THREAD

**Issue by ragnarfrosti** [verbb/Events#61]
### Description
When using project config in the craft project (useProjectConfigFile = true) and the allowAdminChanges is set to false in the production environment it is impossible to add or edit the Ticket types in Events there as those are not saved in the project config but still require allowAdminChanges to be set to true.

So it would be awesome if this could be fixed :)

### Additional info

- Plugin version: 1.4.11
- Craft version: 3.4.23

**Comment by engram-design** [comment]
This is actually semi-intentional, because under the hood ticket types are actually elements, and therefore content. As such, they can't be stored in the project config.

I'm going to have to re-enable editing of ticket types with `allowAdminChanges` as this is technically fine to do.

They should be editable in [1.4.12](https://github.com/verbb/events/releases/tag/1.4.12)

**Comment by ragnarfrosti** [comment]
That sounds even better :)
