### ISSUE TITLE
Paginating events combined with standard Craft entries

### ISSUE THREAD

**Issue by remcoov** [verbb/Events#96]
**Description**
Hi. I'm running into a bit of a problem here: i want to paginate (verbb) events combined with normal news entries. So for example:

```
{% set eventsAndNews = craft.events.events().limit(null).all() | merge(craft.entries.section('news').limit(null).all()) %}
```

Now, when doing a merge, this creates an array - which doesn't work with paginate - so we get the error:

```
Argument 1 passed to craft\helpers\Template::paginateQuery() must implement interface yii\db\QueryInterface, array given
```

I do know there is the possibility to merge queries and then query Craft with all the id's from the array, but this does not work...

```
{% set posts = craft.entries.id( eventsAndNews ) %}
{% paginate posts.limit(12) as pageInfo, pageEntries %}
```
..  because events aren't found in `craft.entries`, but `craft.events`.

Thanks in advance.

**Additional info**
- Plugin version: 1.4.20
- Craft version: 3.7.21
- Multi-site: No

**Comment by engram-design** [comment]
I don't believe you can paginate two different types of elements together, sorry.

However in Craft 3 I believe you can paginate an array, which should work in this case https://gist.github.com/juban/a55781d49f2f68ec3ca47979bcaaa49a but that's also pretty inefficient, because you're not making use of the pagination aspect of the query. You're querying **all** elements of your entries call, and your events call, and then only limiting a certain number to display on the page.
